# NumPy Fundamentals: Locating Array Values
Please complete this assignment with your small group. Discussion is encouraged and a completed version is due before the next class.

In [1]:
import numpy as np

In [2]:
my_array = np.array([[12, 73, 68], [33, 25, 1], [54, 46, 92]])
my_array

array([[12, 73, 68],
       [33, 25,  1],
       [54, 46, 92]])

## Finding Minimum and Maximum Values


In [3]:
print(f"The smallest element is: {np.min(my_array)}")

The smallest element is: 1


In [4]:
print(f"The smallest element is at index: {np.argmin(my_array)}")

The smallest element is at index: 5


In [5]:
my_flat_array = my_array.flatten()
print(f"Flat array: {my_flat_array}")

Flat array: [12 73 68 33 25  1 54 46 92]


In [6]:
print(my_flat_array[5])

1


In [7]:
print(f"The smallest elements in each row: {np.min(my_array, axis = 1)}")
print(f"The smallest elements in each column: {np.min(my_array, axis = 0)}")

The smallest elements in each row: [12  1 46]
The smallest elements in each column: [12 25  1]


### Q.1 Please find the largest value in `my_array`, the index of the largest value, and the largest values in each column

In [8]:
print(f"The largest element in my_array is: {np.max(my_array)}")
print(f"The largest element in my_array is at index: {np.argmax(my_array)}")
print(f"The largest elements in each column are: {np.max(my_array, axis=0)}")

The largest element in my_array is: 92
The largest element in my_array is at index: 8
The largest elements in each column are: [54 73 92]


In [9]:
new_array = np.array([[-18, 13, 83, 11], [28, 18, 12, -16]])
new_array

array([[-18,  13,  83,  11],
       [ 28,  18,  12, -16]])

In [10]:
np.where(new_array > 20)

(array([0, 1]), array([2, 0]))

In [11]:
np.argwhere(new_array > 20)

array([[0, 2],
       [1, 0]])

In [12]:
np.nonzero(new_array)

(array([0, 0, 0, 0, 1, 1, 1, 1]), array([0, 1, 2, 3, 0, 1, 2, 3]))

In [13]:
print(np.where(new_array != 0))

(array([0, 0, 0, 0, 1, 1, 1, 1]), array([0, 1, 2, 3, 0, 1, 2, 3]))

In [14]:
np.sort(new_array)

array([[-18,  11,  13,  83],
       [-16,  12,  18,  28]])

In [15]:
print(np.sort(new_array, axis=0))
print(np.sort(new_array, axis=1))

[[-18  13  12 -16]
 [ 28  18  83  11]]
[[-18  11  13  83]
 [-16  12  18  28]]


### Q.3 What rules does NumPy seem to be following when sorting?

### A.3 NumPy sorts along the specified axis. By default (axis=None), it flattens the array and sorts all values. When axis=0, it sorts each column independently. When axis=1, it sorts each row independently.

### Q.4 What impact does changing the `axis` argument have?

### A.4 Changing the `axis` determines whether sorting occurs along rows (axis=1) or columns (axis=0). Each row or column is sorted independently.

In [16]:
customers = np.array([['Dave','4101'],['Gwendolyn','3222'],['Anne','2315']])

In [17]:
gwen_id_index = np.argwhere(customers=='3222') 
print(gwen_id_index)

In [18]:
gwen_id_row = gwen_id_index[0,0] 
gwen_id_col = gwen_id_index[0,1] 
print(f"Gwen's ID is stored at index: { gwen_id_row },{ gwen_id_col }")

In [19]:
anne_name_index = np.argwhere(customers=='Anne')
print(anne_name_index)

[[2 0]]


In [20]:
anne_data = customers[anne_name_index[0,0]] 
print(f"Anne's database entry: { anne_data }")