# NumPy Fundamentals: Manipulating Matrices
Please follow the instructions and uncomment the skeleton code as necessary.

This assignment is due in addition to the small group assignment before the next class

In [1]:
import numpy as np

In [2]:
# Create a 3x3x3 np.array
my_array = np.array([[[1]], [[2]], [[3]]]) * np.ones((3,3,3))
print(my_array)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]]]


## Multidimensional Indexing

In [3]:
# Q.1 Print the value 2.0
print(my_array[1,0,0])

In [5]:
# Q.2 Print the 3x3 array of all 2's
print(my_array[1,:,:])

In [7]:
# Q.3 Add 5 to every other element
my_array = np.array([[[1]], [[2]], [[3]]]) * np.ones((3,3,3))
new_array = my_array.copy()

# Add 5 to the corners
new_array[:, ::2, ::2] += 5
# Add 5 to the center element
new_array[:, 1, 1] += 5

print(new_array)

[[[6. 1. 6.]
  [1. 6. 1.]
  [6. 1. 6.]]

 [[7. 2. 7.]
  [2. 7. 2.]
  [7. 2. 7.]]

 [[8. 3. 8.]
  [3. 8. 3.]
  [8. 3. 8.]]]


## Reshaping Matrices

In [9]:
# Q.4 Create a 1D array from my_array
my_1d_array = my_array.flatten()
print(my_1d_array)

In [11]:
# Q.5 Create a 2D array with 3 rows and 9 columns
my_2d_array = my_array.reshape(3,9)
print(my_2d_array)

In [25]:
# Q.6 Create a new 3D array where each 3x3 sub-array has at least one row [1,2,3]
transposed_array = np.array([[[1,2,3],[1,1,1],[1,1,1]],
                             [[2,2,2],[2,3,1],[2,2,2]],
                             [[3,3,3],[3,1,2],[3,3,3]]])
print(transposed_array)